### ISSUE TITLE
Dashboard sampl - too much custom CSS

### ISSUE THREAD

**Issue by hrstoyanov** [zzseba78/Kick-Off#12]
The Dashboard sample looks pretty good, but I think it uses way too much custom CSS. UIKit 3 provides enough flexibility,  you don't really need that much custom CSS. Anyway the Dashboard sample can be re-worked into a more standard UIKit 3 and perhaps no custom CSS?

Thanks

**Comment by zzseba78** [comment]
Hi @hrstoyanov 
The dashboard layout have some custom css style because it´s needed, applying some custom margins and positioning and responsive behavior. I didn´t use some uikit positioning classes because they use absolute positioning, and i use fixed ...cleaner.
The css for changing "the way it looks" it´s minimal.

**Comment by hrstoyanov** [comment]
I ma close to getting the same dashboard without any custom CSS. I hope to be able to publish it soon.

**Comment by zzseba78** [comment]
Nice!, please notify me when it´s ready.
