### ISSUE TITLE
the cards kick-off page no longer works as pexpected

### ISSUE THREAD

**Issue by viseth** [zzseba78/Kick-Off#25]
Hi,

I've notice that after migrating to the latest ulkit 3 version, the cards search feature no longer works as usual.
Before we where able to display the items while adding letters as well as while removing letters. Now only adding letters works.
Does card.js support the latest version of ulkit 3 ?

Thanks, 
Rgds

**Comment by zzseba78** [comment]
Hi @viseth.
From v3.6.6 is no longer working, seems that don´t let the same active link run twice.

I found a temporary fix, just triggering a click on a hidden link that gives filter 0 and then click back to the link that throws the search.

Maybe it would be nice to filter items in a programmatic way instead of triggering hidden links, but can´t find it on the docs.

Please check the updated version, and if anyone found a clever way, please share it 😃

**Comment by viseth** [comment]
Hi @zzseba78,
Indeed I have noticed that it did no longer work starting from 3.6.6.
Great your workaround worked ! Thanks for your fix 😀 !
